//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietThuaDat
    {
        public int IDThuaDat { get; set; }
        public int IDLoaiDat { get; set; }
        public Nullable<double> DienTich { get; set; }
        public string GhiChu { get; set; }
        public string MucDichSD_ChiTiet { get; set; }
        public Nullable<System.DateTime> NgayHinhThanh { get; set; }
        public Nullable<System.DateTime> SuDungDenNgay { get; set; }
    
        public virtual LoaiDat LoaiDat { get; set; }
        public virtual ThongTinThuaDat ThongTinThuaDat { get; set; }
    }
}
