//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiayChungNhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiayChungNhan()
        {
            this.ThongTinThuaDats = new HashSet<ThongTinThuaDat>();
        }
    
        public int IDGCN { get; set; }
        public Nullable<int> IDHoSo { get; set; }
        public string SoPhatHanhGCN { get; set; }
        public string SoVaoSo { get; set; }
        public Nullable<System.DateTime> NgayKyBia { get; set; }
    
        public virtual HoSo HoSo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinThuaDat> ThongTinThuaDats { get; set; }
    }
}
