//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoSo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoSo()
        {
            this.GiayChungNhans = new HashSet<GiayChungNhan>();
        }
    
        public int IDHoSo { get; set; }
        public Nullable<int> MaHoSo { get; set; }
        public Nullable<int> IDLoaiHoSo { get; set; }
        public Nullable<int> IDPhuongXa { get; set; }
        public string SDTNguoiNopHoSo { get; set; }
        public string NguoiChuyenQSDD { get; set; }
        public Nullable<bool> NguoiChuyenDongSoHuu { get; set; }
        public string NguoiNhanQSDD { get; set; }
        public Nullable<bool> NguoiNhanDongSoHuu { get; set; }
        public Nullable<System.DateTime> NgayNhanHoSo { get; set; }
        public Nullable<System.DateTime> NgayTraKQGiaiQuyetHS { get; set; }
        public Nullable<System.DateTime> NgayBienLai { get; set; }
        public Nullable<System.DateTime> NgayHenTraGiayChungNhan { get; set; }
        public Nullable<bool> PhuongThucTiepNhanHS { get; set; }
        public Nullable<int> SoPhieuChuyen { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public Nullable<int> SoToTrinh { get; set; }
        public Nullable<System.DateTime> NgayToTrinh { get; set; }
        public Nullable<System.DateTime> NgayTraHoSo { get; set; }
        public string NoiDungTraHoSo { get; set; }
        public Nullable<int> IDCanBoTiepNhan { get; set; }
        public Nullable<int> IDCanBoThuLyHoSo { get; set; }
        public Nullable<System.DateTime> NgayTraKetQua { get; set; }
        public Nullable<decimal> LePhi { get; set; }
        public Nullable<System.DateTime> NgayLuuKho { get; set; }
        public Nullable<byte> IDTrangThai { get; set; }
        public Nullable<bool> HoSoTrucTuyen { get; set; }
    
        public virtual CanBo CanBo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiayChungNhan> GiayChungNhans { get; set; }
        public virtual LoaiHoSo LoaiHoSo { get; set; }
        public virtual PhuongXa PhuongXa { get; set; }
        public virtual TrangThaiHoSo TrangThaiHoSo { get; set; }
    }
}
