//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class CanBo
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CanBo()
    {
        this.HoSoes = new HashSet<HoSo>();
        this.PhanQuyenNguoiDungs = new HashSet<PhanQuyenNguoiDung>();
    }

    public int IDCanBo { get; set; }
    public Nullable<int> IDTo { get; set; }
    public string HoTenCanBo { get; set; }
    public Nullable<System.DateTime> NgaySinh { get; set; }
    public Nullable<bool> GioiTinh { get; set; }
    public string SDT { get; set; }
    public string Email { get; set; }
    public string TenDangNhap { get; set; }
    public string MatKhau { get; set; }
    public Nullable<bool> TrangThaiHoatDong { get; set; }
    public Nullable<bool> SuperAdmin { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<HoSo> HoSoes { get; set; }
    public virtual To To { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PhanQuyenNguoiDung> PhanQuyenNguoiDungs { get; set; }
}

public partial class ChiTietThuaDat
{
    public int IDThuaDat { get; set; }
    public int IDLoaiDat { get; set; }
    public Nullable<double> DienTich { get; set; }
    public string GhiChu { get; set; }
    public string MucDichSD_ChiTiet { get; set; }
    public Nullable<System.DateTime> NgayHinhThanh { get; set; }
    public Nullable<System.DateTime> SuDungDenNgay { get; set; }

    public virtual LoaiDat LoaiDat { get; set; }
    public virtual ThongTinThuaDat ThongTinThuaDat { get; set; }
}

public partial class ChucNang
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ChucNang()
    {
        this.PhanQuyenNguoiDungs = new HashSet<PhanQuyenNguoiDung>();
    }

    public int IDChucNang { get; set; }
    public string TenChucNang { get; set; }
    public string TenControler { get; set; }
    public string TenAction { get; set; }
    public Nullable<bool> TrangThai { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PhanQuyenNguoiDung> PhanQuyenNguoiDungs { get; set; }
}

public partial class ChuSuDung
{
    public int IDHoGiaDinh { get; set; }
    public string TenChuHo { get; set; }
}

public partial class GiayChungNhan
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public GiayChungNhan()
    {
        this.ThongTinThuaDats = new HashSet<ThongTinThuaDat>();
    }

    public int IDGCN { get; set; }
    public Nullable<int> IDHoSo { get; set; }
    public string SoPhatHanhGCN { get; set; }
    public string SoVaoSo { get; set; }
    public Nullable<System.DateTime> NgayKyBia { get; set; }

    public virtual HoSo HoSo { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ThongTinThuaDat> ThongTinThuaDats { get; set; }
}

public partial class HoSo
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public HoSo()
    {
        this.GiayChungNhans = new HashSet<GiayChungNhan>();
    }

    public int IDHoSo { get; set; }
    public Nullable<int> MaHoSo { get; set; }
    public Nullable<int> IDLoaiHoSo { get; set; }
    public Nullable<int> IDPhuongXa { get; set; }
    public string SDTNguoiNopHoSo { get; set; }
    public string NguoiChuyenQSDD { get; set; }
    public Nullable<bool> NguoiChuyenDongSoHuu { get; set; }
    public string NguoiNhanQSDD { get; set; }
    public Nullable<bool> NguoiNhanDongSoHuu { get; set; }
    public Nullable<System.DateTime> NgayNhanHoSo { get; set; }
    public Nullable<System.DateTime> NgayTraKQGiaiQuyetHS { get; set; }
    public Nullable<System.DateTime> NgayBienLai { get; set; }
    public Nullable<System.DateTime> NgayHenTraGiayChungNhan { get; set; }
    public Nullable<bool> PhuongThucTiepNhanHS { get; set; }
    public Nullable<int> SoPhieuChuyen { get; set; }
    public Nullable<System.DateTime> NgayGiao { get; set; }
    public Nullable<int> SoToTrinh { get; set; }
    public Nullable<System.DateTime> NgayToTrinh { get; set; }
    public Nullable<System.DateTime> NgayTraHoSo { get; set; }
    public string NoiDungTraHoSo { get; set; }
    public Nullable<int> IDCanBoTiepNhan { get; set; }
    public Nullable<int> IDCanBoThuLyHoSo { get; set; }
    public Nullable<System.DateTime> NgayTraKetQua { get; set; }
    public Nullable<decimal> LePhi { get; set; }
    public Nullable<System.DateTime> NgayLuuKho { get; set; }
    public Nullable<byte> IDTrangThai { get; set; }
    public Nullable<bool> HoSoTrucTuyen { get; set; }

    public virtual CanBo CanBo { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<GiayChungNhan> GiayChungNhans { get; set; }
    public virtual LoaiHoSo LoaiHoSo { get; set; }
    public virtual PhuongXa PhuongXa { get; set; }
    public virtual TrangThaiHoSo TrangThaiHoSo { get; set; }
}

public partial class LoaiDat
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public LoaiDat()
    {
        this.ChiTietThuaDats = new HashSet<ChiTietThuaDat>();
    }

    public int IDLoaiDat { get; set; }
    public string TenLoaiDat { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ChiTietThuaDat> ChiTietThuaDats { get; set; }
}

public partial class LoaiHoSo
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public LoaiHoSo()
    {
        this.HoSoes = new HashSet<HoSo>();
    }

    public int IDLoaiHoSo { get; set; }
    public string TenLoaiHoSo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<HoSo> HoSoes { get; set; }
}

public partial class PhanQuyenNguoiDung
{
    public int IDCanBo { get; set; }
    public int IDChucNang { get; set; }
    public bool DuocXem { get; set; }
    public bool DuocSua { get; set; }

    public virtual CanBo CanBo { get; set; }
    public virtual ChucNang ChucNang { get; set; }
}

public partial class PhuongXa
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PhuongXa()
    {
        this.HoSoes = new HashSet<HoSo>();
    }

    public int IDPhuongXa { get; set; }
    public string TenPhuongXa { get; set; }
    public string GhiChu { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<HoSo> HoSoes { get; set; }
}

public partial class To
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public To()
    {
        this.CanBoes = new HashSet<CanBo>();
    }

    public int IDTo { get; set; }
    public string TenTo { get; set; }
    public Nullable<int> IDCanBo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CanBo> CanBoes { get; set; }
}

public partial class ThongTinThuaDat
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ThongTinThuaDat()
    {
        this.ChiTietThuaDats = new HashSet<ChiTietThuaDat>();
    }

    public int IDThuaDat { get; set; }
    public Nullable<int> IDHoSo { get; set; }
    public Nullable<int> IDGCN { get; set; }
    public string ToBanDoSo { get; set; }
    public string ThuaDatSo { get; set; }
    public Nullable<double> TongDienTich { get; set; }
    public string QuaTrinhSuDung { get; set; }
    public string DiaChi { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ChiTietThuaDat> ChiTietThuaDats { get; set; }
    public virtual GiayChungNhan GiayChungNhan { get; set; }
}

public partial class TrangThaiHoSo
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TrangThaiHoSo()
    {
        this.HoSoes = new HashSet<HoSo>();
    }

    public byte IDTrangThai { get; set; }
    public string TenTrangThai { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<HoSo> HoSoes { get; set; }
}

public partial class vChiTietThuaDat
{
    public int IDThuaDat { get; set; }
    public int IDLoaiDat { get; set; }
    public string TenLoaiDat { get; set; }
    public Nullable<double> DienTich { get; set; }
    public string GhiChu { get; set; }
    public string MucDichSD_ChiTiet { get; set; }
    public Nullable<System.DateTime> NgayHinhThanh { get; set; }
    public Nullable<System.DateTime> SuDungDenNgay { get; set; }
}

public partial class vDanhSachHoSo_TiepNhan
{
    public int IDHoSo { get; set; }
    public Nullable<int> MaHoSo { get; set; }
    public Nullable<int> IDLoaiHoSo { get; set; }
    public string TenLoaiHoSo { get; set; }
    public Nullable<int> IDPhuongXa { get; set; }
    public string TenPhuongXa { get; set; }
    public string SDTNguoiNopHoSo { get; set; }
    public string NguoiChuyenQSDD { get; set; }
    public Nullable<bool> NguoiChuyenDongSoHuu { get; set; }
    public string NguoiNhanQSDD { get; set; }
    public Nullable<bool> NguoiNhanDongSoHuu { get; set; }
    public string NgayNhanHoSo { get; set; }
    public string NgayTraHoSo { get; set; }
    public Nullable<bool> PhuongThucTiepNhanHS { get; set; }
    public Nullable<int> IDCanBoTiepNhan { get; set; }
    public string CanBoTiepNhan { get; set; }
    public Nullable<byte> IDTrangThai { get; set; }
    public string TenTrangThai { get; set; }
    public string TomTatHoSo { get; set; }
}

public partial class vGiayChungNhan
{
    public int IDGCN { get; set; }
    public Nullable<int> IDHoSo { get; set; }
    public string SoPhatHanhGCN { get; set; }
    public string SoVaoSo { get; set; }
    public string NgayKyBia { get; set; }
}

public partial class vHoSo
{
    public int IDHoSo { get; set; }
    public Nullable<int> MaHoSo { get; set; }
    public Nullable<int> IDLoaiHoSo { get; set; }
    public string TenLoaiHoSo { get; set; }
    public Nullable<int> IDPhuongXa { get; set; }
    public string TenPhuongXa { get; set; }
    public string SDTNguoiNopHoSo { get; set; }
    public string NguoiChuyenQSDD { get; set; }
    public Nullable<bool> NguoiChuyenDongSoHuu { get; set; }
    public string NguoiNhanQSDD { get; set; }
    public Nullable<bool> NguoiNhanDongSoHuu { get; set; }
    public Nullable<System.DateTime> NgayNhanHoSo { get; set; }
    public Nullable<System.DateTime> NgayTraKQGiaiQuyetHS { get; set; }
    public Nullable<System.DateTime> NgayBienLai { get; set; }
    public string NgayBienLai_Text { get; set; }
    public Nullable<bool> PhuongThucTiepNhanHS { get; set; }
    public string TenPhuongThucTiepNhanHS { get; set; }
    public Nullable<int> SoPhieuChuyen { get; set; }
    public Nullable<System.DateTime> NgayGiao { get; set; }
    public Nullable<int> SoToTrinh { get; set; }
    public Nullable<System.DateTime> NgayToTrinh { get; set; }
    public Nullable<System.DateTime> NgayTraHoSo { get; set; }
    public string NoiDungTraHoSo { get; set; }
    public Nullable<int> IDCanBoTiepNhan { get; set; }
    public Nullable<int> IDCanBoThuLyHoSo { get; set; }
    public Nullable<System.DateTime> NgayTraKetQua { get; set; }
    public Nullable<decimal> LePhi { get; set; }
    public Nullable<System.DateTime> NgayLuuKho { get; set; }
    public Nullable<byte> IDTrangThai { get; set; }
    public string TenTrangThai { get; set; }
    public Nullable<System.DateTime> NgayHenTraGiayChungNhan { get; set; }
    public string NgayHenTraGiayChungNhan_Text { get; set; }
    public string TomTatHoSo { get; set; }
    public string CanBoTiepNhan { get; set; }
    public string CanBoThuLy { get; set; }
}

public partial class vThongTinThuaDat
{
    public int IDThuaDat { get; set; }
    public Nullable<int> IDHoSo { get; set; }
    public Nullable<int> IDGCN { get; set; }
    public string ToBanDoSo { get; set; }
    public string ThuaDatSo { get; set; }
    public Nullable<double> TongDienTich { get; set; }
    public string QuaTrinhSuDung { get; set; }
    public string TomTatThuaDat { get; set; }
}
