//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyenNguoiDung
    {
        public int IDCanBo { get; set; }
        public int IDChucNang { get; set; }
        public bool DuocXem { get; set; }
        public bool DuocSua { get; set; }
    
        public virtual CanBo CanBo { get; set; }
        public virtual ChucNang ChucNang { get; set; }
    }
}
