//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDanhSachHoSo_TiepNhan
    {
        public int IDHoSo { get; set; }
        public Nullable<int> MaHoSo { get; set; }
        public Nullable<int> IDLoaiHoSo { get; set; }
        public string TenLoaiHoSo { get; set; }
        public Nullable<int> IDPhuongXa { get; set; }
        public string TenPhuongXa { get; set; }
        public string SDTNguoiNopHoSo { get; set; }
        public string NguoiChuyenQSDD { get; set; }
        public Nullable<bool> NguoiChuyenDongSoHuu { get; set; }
        public string NguoiNhanQSDD { get; set; }
        public Nullable<bool> NguoiNhanDongSoHuu { get; set; }
        public string NgayNhanHoSo { get; set; }
        public string NgayTraHoSo { get; set; }
        public Nullable<bool> PhuongThucTiepNhanHS { get; set; }
        public Nullable<int> IDCanBoTiepNhan { get; set; }
        public string CanBoTiepNhan { get; set; }
        public Nullable<byte> IDTrangThai { get; set; }
        public string TenTrangThai { get; set; }
        public string TomTatHoSo { get; set; }
    }
}
