//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vGiayChungNhan
    {
        public int IDGCN { get; set; }
        public Nullable<int> IDHoSo { get; set; }
        public string SoPhatHanhGCN { get; set; }
        public string SoVaoSo { get; set; }
        public string NgayKyBia { get; set; }
    }
}
