//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vHoSo
    {
        public int IDHoSo { get; set; }
        public Nullable<int> MaHoSo { get; set; }
        public Nullable<int> IDLoaiHoSo { get; set; }
        public string TenLoaiHoSo { get; set; }
        public Nullable<int> IDPhuongXa { get; set; }
        public string TenPhuongXa { get; set; }
        public string SDTNguoiNopHoSo { get; set; }
        public string NguoiChuyenQSDD { get; set; }
        public Nullable<bool> NguoiChuyenDongSoHuu { get; set; }
        public string NguoiNhanQSDD { get; set; }
        public Nullable<bool> NguoiNhanDongSoHuu { get; set; }
        public Nullable<System.DateTime> NgayNhanHoSo { get; set; }
        public Nullable<System.DateTime> NgayTraKQGiaiQuyetHS { get; set; }
        public Nullable<System.DateTime> NgayBienLai { get; set; }
        public string NgayBienLai_Text { get; set; }
        public Nullable<bool> PhuongThucTiepNhanHS { get; set; }
        public string TenPhuongThucTiepNhanHS { get; set; }
        public Nullable<int> SoPhieuChuyen { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public Nullable<int> SoToTrinh { get; set; }
        public Nullable<System.DateTime> NgayToTrinh { get; set; }
        public Nullable<System.DateTime> NgayTraHoSo { get; set; }
        public string NoiDungTraHoSo { get; set; }
        public Nullable<int> IDCanBoTiepNhan { get; set; }
        public Nullable<int> IDCanBoThuLyHoSo { get; set; }
        public Nullable<System.DateTime> NgayTraKetQua { get; set; }
        public Nullable<decimal> LePhi { get; set; }
        public Nullable<System.DateTime> NgayLuuKho { get; set; }
        public Nullable<byte> IDTrangThai { get; set; }
        public string TenTrangThai { get; set; }
        public Nullable<System.DateTime> NgayHenTraGiayChungNhan { get; set; }
        public string NgayHenTraGiayChungNhan_Text { get; set; }
        public string TomTatHoSo { get; set; }
        public string CanBoTiepNhan { get; set; }
        public string CanBoThuLy { get; set; }
    }
}
