//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vThongTinThuaDat
    {
        public int IDThuaDat { get; set; }
        public Nullable<int> IDHoSo { get; set; }
        public Nullable<int> IDGCN { get; set; }
        public string ToBanDoSo { get; set; }
        public string ThuaDatSo { get; set; }
        public Nullable<double> TongDienTich { get; set; }
        public string QuaTrinhSuDung { get; set; }
        public string TomTatThuaDat { get; set; }
    }
}
